### ISSUE TITLE
question on OCI CLI configuration

### ISSUE THREAD

**Issue by dhoogfr** [oracle-samples/oci-vscode-toolkit#10]
I already have the OCI CLI installed on my workstation via pip.
After I installed VS Code toolkit, I keeps asking me if I want to install the OCI CLI as part of the toolkit

Is there a way to disable this and still have the CLI integration functioning within VS Code?
The installation was done in the default directories and are the same as the integration has as default.
So would actually expect the integration to notice that these are already installed

**Comment by NiviPari** [comment]
@dhoogfr  what is the OS being used ?

**Comment by dhoogfr** [comment]
@NiviPari The OS is Linux (Linux Mint / Ubuntu)

**Comment by jyotisaini** [comment]
Thanks for reporting the issue @dhoogfr. We do check if the user has the OCI CLI installed already.  We will try to reproduce it and post the update here.

**Comment by dvondros** [comment]
same issue with Windows 11 and VS Code 1.79.
Thank you for any update.

**Comment by sreeharshakakani** [comment]
@dhoogfr @dhoogfr Can you please try it with v1.0.2

**Comment by LavanyaSiliveri** [comment]
I am facing below issue, when I allow it to install oci-cli as part of oci tool kit

uccessfully installed PyYAML-6.0.1 arrow-1.3.0 certifi-2024.2.2 cffi-1.16.0 circuitbreaker-1.4.0 click-8.0.4 cryptography-42.0.5 jmespath-0.10.0 oci-2.125.3 oci_cli-3.39.1 prompt-toolkit-3.0.29 pyOpenSSL-24.1.0 pycparser-2.22 python-dateutil-2.9.0.post0 pytz-2024.1 six-1.16.0 terminaltables-3.1.10 types-python-dateutil-2.9.0.20240316 wcwidth-0.2.13
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/var/folders/w3/7gzsk14d07xc4p1td1pyb1200000gn/T/oci_cli_install_tmp_XXXX.LHrr2CWjEf", line 722, in <module>
    main()
  File "/var/folders/w3/7gzsk14d07xc4p1td1pyb1200000gn/T/oci_cli_install_tmp_XXXX.LHrr2CWjEf", line 705, in main
    venv_site_packages_directory = subprocess.check_output([venv_python_executable, '-c', 'from distutils.sysconfig import get_python_lib; print(get_python_lib())']).strip()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/lavanyasiliveri/lib/oracle-cli/bin/python', '-c', 'from distutils.sysconfig import get_python_lib; print(get_python_lib())']' returned non-zero exit status 1.
